---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
labels:
  org.opencontainers.image.source: https://github.com/skull199/hassio-duckdns-updater
  org.opencontainers.image.licenses: MIT
